# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
config.vm.box = "boxcutter/centos71"

  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
  end

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "1024"]
    vb.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate//git", "1"]
  end

  config.vm.synced_folder "../../../", "/git"
  config.vm.synced_folder "salt/roots/", "/srv/salt/"
  config.vm.provision :salt do |salt|
    salt.bootstrap_options = "-F -c /tmp -P"
    salt.minion_config = "salt/minion"
    salt.run_highstate = false
  end
  config.vm.network :forwarded_port, guest: 22, host: 2201, id: "ssh", auto_correct: true
end
