#!/bin/bash

### BEGIN INIT INFO
# Provides:          cephrestapi
# Required-Start:    $network
# Required-Stop:     $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Ceph REST API
# Description:       Ceph REST API
### END INIT INFO

DESC="Ceph REST API"

# set to --threads <n> for multithreaded serving
THREADS=

SOCKNAME=/tmp/cephrestapi.sock
PIDFILE=/var/run/cephrestapi.uwsgi.pid
LOGFILE=/var/log/ceph/uwsgi.log

start() {
	uwsgi --plugin python -s $SOCKNAME --chmod-socket=777 \
		--wsgi-file /etc/nginx/cephrestwsgi.py --callable app &
	echo $? > $PIDFILE
}

stop() {
	if [ -f $PIDFILE ] ; then
		uwsgi --stop $PIDFILE
	fi
}

case "$1" in
  start)
	start
	;;

  stop)
	stop
	;;

  reload|restart)
	stop
	start
	;;

  *)
	echo "Usage: cephrestapi {start|stop|restart|reload}"
	exit 1
	;;
esac

exit 0
