#!/bin/bash -e

unconfigure_diamond()
{
	[ -e /etc/diamond/diamond.conf ] && \
		rm -f /etc/diamond/diamond.conf
	[ -e /etc/default/diamond.orig ] && \
		mv /etc/default/diamond.orig /etc/default/diamond
}

case "$1" in
	remove)
		unconfigure_diamond
		[ -x /sbin/stop ] && stop diamond
		;;
	upgrade|deconfigure)
		:
		;;
	*)
		echo "prerm called with unknown argument $1" >&2
		exit 1
		;;
esac

#DEBHELPER#

exit 0
