#!/bin/bash

case "$1" in
	remove)
		a2dismod proxy
		a2dissite calamari.conf
		a2dissite graphite.conf
		a2ensite 000-default
		service apache2 restart
		/etc/init.d/carbon-cache stop
		/etc/init.d/kraken stop
		update-rc.d -f carbon-cache remove
		update-rc.d -f kraken remove
		;;
	upgrade|deconfigure)
		:
		;;
	*)
		echo "prerm called with unknown argument $1" >&2
		exit 1
		;;
esac

#DEBHELPER#

exit 0
