# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  if ENV['RHEL7_BOX_PATH'] == nil
    box_url = "file:/home/jenkins-build/rhel7.box"
  else
    box_url = ENV['RHEL7_BOX_PATH']
  end
  config.vm.box_url = box_url
  config.vm.box = "rhel7"

  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
  end

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "1024"]
    vb.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate//git", "1"]
  end

  config.vm.synced_folder "../../../", "/git"
  config.vm.synced_folder "salt/roots/", "/srv/salt/"
  config.vm.provision :salt do |salt|
    salt.minion_config = "salt/minion"
    salt.run_highstate = false
    salt.bootstrap_script = "../urllib-bootstrap-salt.sh"
    salt.install_type = "git"
    salt.install_args = "develop"
  end
  config.vm.network :forwarded_port, guest: 22, host: 2203, id: "ssh", auto_correct: true
end
