build_deps:
  pkg.installed:
    - pkgs:
      - git
      - createrepo
      - rpm-build
      - gcc
      - gcc-c++
      - python-virtualenv
      - python-devel
      - swig
      - zeromq3-devel
      - pycairo-devel
      - make
      - postgresql-devel
      - Cython
      - python-mock
      - python-configobj
      - python-sphinx
      - cairo-devel
      - m2crypto
      - python-crypto
      - redhat-lsb-core
      - hardlink
      - httpd
