# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"

  # Use a bridged network so that external Ceph servers can connect to
  # salt master on this VM.
  config.vm.network "public_network"

  config.vm.synced_folder "../../", "/calamari.git"
  config.vm.synced_folder "salt/roots/", "/srv/salt/"
  config.vm.provision "shell",
    inline: "/bin/bash /calamari.git/vps_bootstrap.sh"

end
